config/routes.rb
Rails.application.routes.draw do
  
  #root homepage
  root 'pages#home'
  
  #about page
  get 'about' => 'pages#about'
  
  #help page
  get 'help' => 'pages#help'
  
  #privacy page
  get 'privacy' => 'pages#privacy'
  #university and course pages
  get 'courses' => 'pages#courses'
  get 'unis' => 'pages#unis'
  
  #keyword search
  get 'keywordsearch' => 'searches#keywordsearch'

  #Users and Devise authentication system routes
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  get '/users/sign_out' => 'devise/sessions#destroy' 
  resources :users, :only => [:show, :index]
  
  #rails_admin gem: Admin dashboard route
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  #User analysis page for admin users
  get 'analysis' => 'analysis#user_analysis'
  
  #Search and Save search result to profile routes
  match 'users/:id/save_search' => 'users#save_search', :as => :save_search, via: 'get'
  resources :searches, only: [:destroy]

  #advanced search route
  get 'adsearch' => 'searches#adsearch'
  #individual degree pages route
  get 'coursepage' => 'degree#coursepage'
  
  #quiz route
  get 'quiz' => 'personquiz#pquiz'
  get 'sbear' => 'personquiz#sbear'
  get 'rpanda' => 'personquiz#rpanda'
  get 'alpach' => 'personquiz#alpach'
  get 'tiger' => 'personquiz#tiger'
  
  #contact form routes
  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]
  
  #error pages routes
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
  match "/422", :to => "errors#unprocessable_entity", :via => :all

  #Recommender system routes
  get 'new' => 'searches#new'
  get 'ques' => 'recquiz#ques'
  get 'result' => 'searches#result'
  get 'bio' => 'quiz#bio'
  get 'phys' => 'quiz#phys'
  get 'math' => 'quiz#math'
  get 'hum' => 'quiz#hum'
  get 'law' => 'quiz#law'
  get 'lin' => 'quiz#lin'
  get 'lan' => 'quiz#lan'
  get 'art' => 'quiz#art'
  get 'draw' => 'quiz#draw'
  get 'mainquiz' => 'quiz#mainquiz'

end

app/models/user.rb
class User < ActiveRecord::Base
  #Devise authentication system
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :confirmable
         
  TEMP_EMAIL_PREFIX = 'change@me'
  TEMP_EMAIL_REGEX = /\Achange@me/


  validates_format_of :email, :without => TEMP_EMAIL_REGEX, on: :update

  def self.find_for_oauth(auth, signed_in_resource = nil)

    # Get the identity and user if they exist
    identity = Identity.find_for_oauth(auth)

    # If a signed_in_resource is provided it always overrides the existing user
    # to prevent the identity being locked with accidentally created accounts.
    # Note that this may leave zombie accounts (with no associated identity) which
    # can be cleaned up at a later date.
    user = signed_in_resource ? signed_in_resource : identity.user

    # Create the user if needed
    if user.nil?

      # Get the existing user by email if the provider gives us a verified email.
      # If no verified email was provided we assign a temporary email and ask the
      # user to verify it on the next step via UsersController.finish_signup
      email_is_verified = auth.info.email && (auth.info.verified || auth.info.verified_email)
      email = auth.info.email if email_is_verified
      user = User.where(:email => email).first if email

      # Create the user if it's a new registration
      if user.nil?
        user = User.new(
          name: auth.extra.raw_info.name,
          #username: auth.info.nickname || auth.uid,
          email: email ? email : "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com",
          password: Devise.friendly_token[0,20]
        )
        user.skip_confirmation!
        user.save!
      end
    end

    # Associate the identity with the user if needed
    if identity.user != user
      identity.user = user
      identity.save!
    end
    user
  end

  def email_verified?
    self.email && self.email !~ TEMP_EMAIL_REGEX
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update]
  
  #breadcrumbs
  add_crumb "Home", '/'
  
  #user's individual My profile page
  def show
    #breadcrumbs
    add_crumb "My Profile", user_path, links: false
    @user = current_user
        #breadcrumbs
    add_crumb "My Profile", user_path
    add_crumb "My Saved Searches", save_search_path, links: false
    @showsearches = Search.all.where(users_id: current_user)
  end
  
  #user's saved searches page
  def save_search
    #breadcrumbs
    add_crumb "My Profile", user_path
    add_crumb "My Saved Searches", save_search_path, links: false
    @showsearches = Search.all.where(users_id: current_user)
  end
  
  #user's edit my personal details
  def edit
    authorize! :update, @user
  end
  #user's edit my personal details
  def update
    authorize! :update, @user
    respond_to do |format|
      if @user.update(user_params)
        sign_in(@user == current_user ? @user : current_user, :bypass => true)
        format.html { redirect_to @user, notice: 'Your profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  #delete a user functionality, admin can delete users through their access to the admin dashboard
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end
  
  private
  #devise to access the right user
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      accessible = [ :name, :email, :dob, :postcode, :gender, :id ] 
      accessible << [ :password, :password_confirmation ] unless params[:user][:password].blank?
      params.require(:user).permit(accessible)
    end
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, class: "gravatar")
  end
end

app/views/users/save_search.html.erb
<!--Saved searches page in each users' profile Title --> 
<% provide(:title, 'My Saved Searches') %>

<!-- Breadcrumbs -->
<div class= "row">
  <br>
  <%= link_to "Back", :back %>
</div>  
  
<!-- Page Content -->
<div class= "row">
  <h1>My Saved Searches</h1>
    <%= image_tag "line.png" , :alt => "logo"%>  

    <!---Saved Searches Table-->
    <% if @showsearches != nil %>
      <table>
        <thead>
          <tr>
            <th>Saved Degree</th>
            <th>University Name</th>
            <th>Date / Time</th>
          </tr>
        </thead>
        <tbody>
          <% @showsearches.each do |search| %>
            <tr>
              <td><a href="<%= search.saved_search %>"><%= search.cname %></a></td>
              <td><%= search.uname %></td>
              <td><%= search.created_at %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <% end %>
      <br>
      <%= link_to 'Delete My Saved Searches', search_path, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-default" %>

  <!--Page Breaks -->
  <br><br>
</div>

app/views/users/show.html.erb
<!--Profile Page Title --> 
<% provide(:title, "My Profile") %>




<!--Page information --> 
<div class= "row">
    

</div>

  <div class="row">
    <div class="col-s-5 col-s-5";>
        <div class="gravatar_pro">
              <%= gravatar_for @user %>
              
              <!--Links for all Users -->
               <div class="colorbg"> 
               <div class ="profilep">
                 
                   <%= button_to "Edit my Account Details", edit_user_registration_path(current_user),
                        :class => "probut_button width-180px", :method => :get %>
            
                    <!--limits below to Admin-->
                    <% if current_user.admin? %>
                    
                    <%= button_to "User Analysis", analysis_path,
                    :class => "probut_button width-180px", :method => :get %>
                    <%= button_to "Admin Dashboard", rails_admin_path,
                    :class => "probut_button width-180px", :method => :get %>
                    <% end %>  
                    </div>
              </div>
        </div>
    </div>
  
  

    <div class="col-s-7 col-s-7";>
    <div class ="profilep">  
          <!--Welcoming User -->
          <h2>Hi <%= @user.name %></h2>
          <%= image_tag "lineresults.png" , :alt => "logo"%>
          
                 <div class="colorbg"> 
                        <h3>My Saved Searches</h3>
                        <%= image_tag "lineresults.png" , :alt => "logo"%>  
                        <br><br><br>
                        
                        <!---Saved Searches Table-->
                        <% if @showsearches != nil %>
                            <table>
                              <thead>
                                <tr>
                                  <th>Saved Degree</th>
                                  <th>University Name</th>
                                  <th>Date / Time</th>
                                </tr>
                              </thead>
                              <tbody>
                                <% @showsearches.each do |search| %>
                                  <tr>
                                    <td><a href="<%= search.saved_search %>"><%= search.cname %></a></td>
                                    <td><%= search.uname %></td>
                                    <td><%= search.created_at %></td>
                                  </tr>
                                <% end %>
                              </tbody>
                            </table>
                            <% end %>
                            <br>
                            <%= link_to 'Delete My Saved Searches', search_path, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-default" %>
                      
                        <!--Page Breaks -->
                        <br><br>
              </div>
    </div>
</div>
         