config/routes.rb
Rails.application.routes.draw do
  
  #root homepage
  root 'pages#home'
  
  #about page
  get 'about' => 'pages#about'
  
  #help page
  get 'help' => 'pages#help'
  
  #privacy page
  get 'privacy' => 'pages#privacy'
  #university and course pages
  get 'courses' => 'pages#courses'
  get 'unis' => 'pages#unis'
  
  #keyword search
  get 'keywordsearch' => 'searches#keywordsearch'

  #Users and Devise authentication system routes
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  get '/users/sign_out' => 'devise/sessions#destroy' 
  resources :users, :only => [:show, :index]
  
  #rails_admin gem: Admin dashboard route
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  #User analysis page for admin users
  get 'analysis' => 'analysis#user_analysis'
  
  #Search and Save search result to profile routes
  match 'users/:id/save_search' => 'users#save_search', :as => :save_search, via: 'get'
  resources :searches, only: [:destroy]

  #advanced search route
  get 'adsearch' => 'searches#adsearch'
  #individual degree pages route
  get 'coursepage' => 'degree#coursepage'
  
  #quiz route
  get 'quiz' => 'personquiz#pquiz'
  get 'sbear' => 'personquiz#sbear'
  get 'rpanda' => 'personquiz#rpanda'
  get 'alpach' => 'personquiz#alpach'
  get 'tiger' => 'personquiz#tiger'
  
  #contact form routes
  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]
  
  #error pages routes
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
  match "/422", :to => "errors#unprocessable_entity", :via => :all

  #Recommender system routes
  get 'new' => 'searches#new'
  get 'ques' => 'recquiz#ques'
  get 'result' => 'searches#result'
  get 'bio' => 'quiz#bio'
  get 'phys' => 'quiz#phys'
  get 'math' => 'quiz#math'
  get 'hum' => 'quiz#hum'
  get 'law' => 'quiz#law'
  get 'lin' => 'quiz#lin'
  get 'lan' => 'quiz#lan'
  get 'art' => 'quiz#art'
  get 'draw' => 'quiz#draw'
  get 'mainquiz' => 'quiz#mainquiz'

end

app/models/search.rb
class Search < ActiveRecord::Base
    validates :saved_search, presence: true
    validates :users_id, presence: true
    validates :uname, presence: true
    validates :cname, presence: true
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  
  #breadcrumbs
  add_crumb "Home", '/'
 
  def adsearch
    #breadcrumbs
    add_crumb "Detailed Search", adsearch_path, links: false
    
    #Ransack search: keyword searches for degree title and university name
    @adsearch = Degree.ransack(params[:q])
    ransackresults = @adsearch.result

    #define uni region for advanced search 
    @northern = ["The University of Aberdeen", "University of the Highlands and Islands", "The Open University"]
    @southern = ["SRUC - Scotlands Rural College", "University of the West of Scotland", "The Open University"]
    @central = ["Abertay University", "City of Glasgow College", "University of Dundee", "The University of Edinburgh",
      "Edinburgh Napier University", "University of Glasgow", "Glasgow Caledonian University", "The Glasgow School of Art",
      "Heriot-Watt University, Edinburgh", "Middlesex University", "Queen Margaret University, Edinburgh", "Robert Gordon University",
      "Royal Conservatoire of Scotland", "SAE Institute", "University of St Andrews", "The University of Stirling",
      "The University of Strathclyde", "The Open University"]
    if params[:uregion]
      @uregion = params[:uregion]
      if @uregion == "Anywhere"
        uregion = Degree.all
      elsif @uregion == "Northern"
        uregion = Degree.all.where(uname: @northern)
      elsif @uregion == "Central belt"
        uregion = Degree.all.where(uname: @central)
      elsif @uregion == "Southern"
        uregion = Degree.all.where(uname: @southern)
      end
    end
    
    #define discipline for the ucas letters
    if params[:discipline]
      @discipline = params[:discipline]
      if @discipline == "Medicine and Dentistry"
        discipline = Degree.where('ucas ILIKE ?', "A%")
      elsif @discipline == "Subjects allied to Medicine"
        discipline = Degree.where('ucas ILIKE ?', "B%")
      elsif @discipline == "Biological Sciences"
        discipline = Degree.where('ucas ILIKE ?', "C%")
      elsif @discipline == "Veterinary Sciences, Agriculture and Related Subjects"
        discipline = Degree.where('ucas ILIKE ?', "D%")
      elsif @discipline == "Physical Sciences"
        discipline = Degree.where('ucas ILIKE ?', "F%")
      elsif @discipline == "Mathematical Sciences"
        discipline = Degree.where('ucas ILIKE ?', "G%")
      elsif @discipline == "Engineering"
        discipline = Degree.where('ucas ILIKE ?', "H%")
      elsif @discipline == "Computer Sciences"
        discipline = Degree.where('ucas ILIKE ?', "I%")
      elsif @discipline == "Technologies"
        discipline = Degree.where('ucas ILIKE ?', "J%")
      elsif @discipline == "Architecture, Building and Planning"
        discipline = Degree.where('ucas ILIKE ?', "K%")
      elsif @discipline == "Social Studies"
        discipline = Degree.where('ucas ILIKE ?', "L%")
      elsif @discipline == "Law"
        discipline = Degree.where('ucas ILIKE ?', "M%")
      elsif @discipline == "Business and Administrative Studies"
        discipline = Degree.where('ucas ILIKE ?', "N%")
      elsif @discipline == "Mass Communication and Documentation"
        discipline = Degree.where('ucas ILIKE ?', "P%")
      elsif @discipline == "Linguistics, Classics and Related Subjects"
        discipline = Degree.where('ucas ILIKE ?', "Q%")
      elsif @discipline == "European Languages, Literature and Related Subjects"
        discipline = Degree.where('ucas ILIKE ?', "R%")
      elsif @discipline == "Eastern, Asiatic, African, American and Australasian Languages, Literature and Related Subjects"
        discipline = Degree.where('ucas ILIKE ?', "T%")
      elsif @discipline == "Historical and Philosophical Studies"
        discipline = Degree.where('ucas ILIKE ?', "V%")
      elsif @discipline == "Creative Arts and Design"
        discipline = Degree.where('ucas ILIKE ?', "W%")
      elsif @discipline == "Education"
        discipline = Degree.where('ucas ILIKE ?', "X%")
      end
    end
    
    #merge all selected and entered values of the advanced serach to do a specific search
    if params[:uregion] != nil
      @data = uregion.merge(ransackresults).merge(discipline)
    end

    #the drop-downs refine by region and discipline will have if not selected otherwise by the user
    #the selected default values of Any and Anywhere, otherwise the selected value persists in the form when the page is reloaded
    if params[:discipline] = nil
      @discipline = "Any"
      @uregion = "Anywhere"
    end
  end

  #recommender system
  def ques
  end
  def results
  end

  #quiz functionality
  def quiz
  end
  
  #delete all my search results functionality
  def destroy
    Search.destroy_all(users_id: current_user)
    redirect_to user_path(current_user)
  end
  
  
  
  def keywordsearch
    @search = Degree.all.select(:uname, :cname, :ucas, :duration, :qualification, :entry).distinct.order(id: :ASC)
    if params[:search]
      @search_degree = Degree.search(params[:search]).order('uname ASC')
    end
  end
  
end

app/helpers/searches_helper.rb
module SearchesHelper
  
  #Ransack search Helper method - not used in the current version used, could be 
  #implemented back in the future if additional fields should be added to the advanced search
  def link_to_add_fields(name, f, type)
    new_object = f.object.send "build_#{type}"
    id = "new_#{type}"
    fields = f.send("#{type}_fields", new_object, child_index: id) do |builder|
      render(type.to_s + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end
  
end

app/views/searches/_condition_fields.html.erb
<!-- Ransack condition fields code, unused at the moment. Could be used in further improvement of the advanced search to add additional fields-->
<div class="field">
  <p>Refinement Criteria (e.g. University Name)</p>
  <%= f.attribute_fields do |a| %>
    <%= a.attribute_select %>
  <% end %>
  
  <p>contains</p>
  <div class="hidden">
    <%= f.predicate_select compounds: false, only: %i(cont) %>
  </div>

  <p>Type in wanted value (e.g. Aberdeen)</p>
  <%= f.value_fields do |v| %>
    <%= v.text_field :value %>
  <% end %>
  <%= link_to "remove", '#', class: "remove_fields" %>
</div>

app/views/searches/_regions.html.erb
<!-- regions map pop up -->

<%= link_to 'Scotland Regions Map?', asset_path('mapscotland.jpg'), rel: 'Shadowbox', :target => "_blank" %>

app/views/searches/adsearch.html.erb
<!-- Advanced search page title  --> 
<% provide(:title, 'Search') %>


<!--Breadcrumbs -->
<br>
<%= link_to "Back", :back %><br><br>

<!--Page title --> 
  <div class ="row">
    <h1>Search</h1>
    <%= image_tag "line.png" , :alt => "line break"%>    
  </div>
  
<!-- Search Categories -->  
  <div class = "row">
    <div class="col-s-4 col-s-4";>
        
        <%= search_form_for @adsearch, url: adsearch_path, method: :get do |f| %>
               
        <!-- Regions defined (hardcoded) for the region dropdown in advanced search -->
        <%= label_tag :uregion, "Refine By Region:" %><br>
        <%= render "regions" %><br>
        <%= select_tag :uregion, options_for_select(["Anywhere", "Northern", "Central belt", "Southern"], selected: @uregion)  %>
        
        <!-- Discipline Categories defined (hardcoded) for the discipline dropdown in advanced search -->
        <%= label_tag :discipline, "Refine By Degree Category:" %><br>
        <%= select_tag :discipline, options_for_select(["Any", "Medicine and Dentistry", "Subjects allied to Medicine", "Biological Sciences",
          "Veterinary Sciences, Agriculture and Related Subjects", "Physical Sciences", "Mathematical Sciences", "Engineering", 
          "Computer Sciences", "Technologies", "Architecture, Building and Planning", "Social Studies", "Law", 
          "Business and Administrative Studies", "Mass Communication and Documentation", "Linguistics, Classics and Related Subjects",
          "European Languages, Literature and Related Subjects", 
          "Eastern, Asiatic, African, American and Australasian Languages, Literature and Related Subjects", 
          "Historical and Philosophical Studies", "Creative Arts and Design", "Education"], selected: @discipline ) %>
      
        <div>
          
            <!-- Ransack Keyword Search for Degree name -->
            <%= f.label :cname_cont, "Degree Name Contains:" %>
            <%= f.text_field :cname_cont, placeholder: "Degree Name" %>
            
        </div>
        
        <div>
          
          <!-- Ransack Keyword Search for University name -->
          <%= f.label :uname_cont, "University Name Contains:" %>
          <%= f.text_field :uname_cont, placeholder: "University Name" %>
        
        </div>
        <!-- Search Button -->
        <div class="actions">
          <%= f.submit "Search", :class => "btn btn-default" %>
          
        </div>
        
      <% end %>
      
    </div>
    
    <!-- Returns results for search -->
    <div class="col-s-8 col-s-8";>
      <% if @data != nil %>
       <div class="colorbg"> 
      <h2>Results:</h2>
      <%= image_tag "line.png" , :alt => "line break"%>    

      
      <!-- Counts how many results there are for each search -->
          
      <div class="resultsclass">
     
      <p><%= @data.count %> results</p>
      <% end %>
  
      <!-- Returns all results which meet the criteria and populates the page with their information -->
      
      <% if @data != nil %>
        <% @data.each do |degree| %>
       
        
          <strong><%= degree.cname %></strong><br>
          <%= degree.uname %><br>
          <%= degree.qualification %><br>
          <%= degree.duration %><br>
          <%= degree.entry %><br>
          <% if user_signed_in? %><br>
          
          <!-- Saves the search result to users profile page if logged in -->
          <%= link_to "Save", coursepage_path(indcoursepage: degree.id), :class => "btn btn-default"%>
      
          <% else %>
          <!-- Text replaces save button if user not logged in, prompting them to log in -->
            <h4> <a href="users/sign_in">Login</a> to save this degree to your Profile page.</h4>
            
            <% end %>
           
          <%= image_tag "lineresults.png" , :alt => "line break"%>    
          <br>
          <% end %>
             
          <% end %>
        </div>
      </div>
    </div>

  </div>

app/views/searches/keywordsearch.html.erb
<!-- Index of all Courses -->
<% provide(:title, "Courses Page") %>


<!--Breadcrumbs -->
<br>
<%= link_to "Back", :back %><br><br>

<!--Page Contents --> 
 
 
  <div class ="row">
    <h1>Degrees Offered</h1>
    <%= image_tag "line.png" , :alt => "line break"%>    
  </div>
  
  <div class ="row">
    
      <!-- Form for Keyword Search, to Querry Database for University courses. It is hidden so as to not appear as a search on the page -->
      <div class = "hidden">         
      <%= form_tag(keywordsearch_path, :method => "get", id: "search-data") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search course" %>
      <%= submit_tag "Search" %>
      <% end %>
      </div>     
      <% if @search_degree != nil %>
      <% end %>
      
      <% if @search_degree != nil %>
        <table border="1" class="table">
          <thead>
            <tr>
              <th>University Name</th>
              <th>Course Name</th>
              <th>Duration</th>
              <th>Qualification</th>
              <th>Entry Requirements</th>
              <th>Course Page</th>
            </tr>
          </thead>
          <tbody>
            <% @search_degree.each do |degree| %>
            <tr>
              <td><%= degree.uname %></td>
              <td><%= degree.cname %></td>
              <td><%= degree.duration %></td>
              <td><%= degree.qualification %></td>
              <td><%= degree.entry %></td>
              <td><%= link_to 'View Course Page on University Website', url_for(degree.url), target: "_blank" %></a></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
    </div>