config/routes.rb
Rails.application.routes.draw do
  
  #root homepage
  root 'pages#home'
  
  #about page
  get 'about' => 'pages#about'
  
  #help page
  get 'help' => 'pages#help'
  
  #privacy page
  get 'privacy' => 'pages#privacy'
  #university and course pages
  get 'courses' => 'pages#courses'
  get 'unis' => 'pages#unis'
  
  #keyword search
  get 'keywordsearch' => 'searches#keywordsearch'

  #Users and Devise authentication system routes
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  get '/users/sign_out' => 'devise/sessions#destroy' 
  resources :users, :only => [:show, :index]
  
  #rails_admin gem: Admin dashboard route
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  #User analysis page for admin users
  get 'analysis' => 'analysis#user_analysis'
  
  #Search and Save search result to profile routes
  match 'users/:id/save_search' => 'users#save_search', :as => :save_search, via: 'get'
  resources :searches, only: [:destroy]

  #advanced search route
  get 'adsearch' => 'searches#adsearch'
  #individual degree pages route
  get 'coursepage' => 'degree#coursepage'
  
  #quiz route
  get 'quiz' => 'personquiz#pquiz'
  get 'sbear' => 'personquiz#sbear'
  get 'rpanda' => 'personquiz#rpanda'
  get 'alpach' => 'personquiz#alpach'
  get 'tiger' => 'personquiz#tiger'
  
  #contact form routes
  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]
  
  #error pages routes
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
  match "/422", :to => "errors#unprocessable_entity", :via => :all

  #Recommender system routes
  get 'new' => 'searches#new'
  get 'ques' => 'recquiz#ques'
  get 'result' => 'searches#result'
  get 'bio' => 'quiz#bio'
  get 'phys' => 'quiz#phys'
  get 'math' => 'quiz#math'
  get 'hum' => 'quiz#hum'
  get 'law' => 'quiz#law'
  get 'lin' => 'quiz#lin'
  get 'lan' => 'quiz#lan'
  get 'art' => 'quiz#art'
  get 'draw' => 'quiz#draw'
  get 'mainquiz' => 'quiz#mainquiz'

end

app/views/layouts/_footer.html.erb
<!-- Footer inserted into each page -->
<div class="footer">
  
  <h1>Copyright &copy; Uni2choose 2016 || <%= link_to "Contact Us", contacts_path %> ||  <%= link_to "Help", help_path %> ||  <%= link_to "Privacy Policy", privacy_path %></h1>
  
  <p>All information regarding universities and degrees was obtained from <a href="https://www.ucas.com/", target="_blank">UCAS</a> and remains the sole property of UCAS and/or the legal licence holders</p>
</div>

app/views/layouts/_navbar.html.erb
<!-- Navigation Bar inserted into each page -->
  <nav class="navbar navbar-fixed-top">
    <nav class="navbar navbar-default">

        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

        </div>
        <!-- Changes nav bar into Hamburger menu -->
        <div class="collapse navbar-collapse" id="myNavbar">
          
          <ul class="nav navbar-nav">
            
            
            <li><%= link_to "Home", root_path %></li>
            
            <li><%= link_to "Universities", unis_path %></li>

            <li><%= link_to "Search", adsearch_path %></li> 
            
            <% if !user_signed_in? %>
            <li><%= link_to "Register", new_user_registration_path %></li>
            <li><%= link_to "Log in", new_user_session_path %></li>
            
            <% else %>
            <li><%= link_to "My Profile", user_path(current_user) %></li>
            <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
            <% end %>
          </ul>
          
        </div>
    </nav>
  </nav>

app/views/layouts/application.html.erb
<!-- Base layout for all Pages -->
<!DOCTYPE html>
<html>

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  
  <!--Title Page info -->
  <title><%= yield(:title) %> | Uni2choose</title>

  <!--JavaScript extentions -->
  <%= javascript_include_tag "https://www.google.com/jsapi", "chartkick" %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true  %>
  <%= csrf_meta_tags %>

</head>

<body>

  <!-- Display Navigation Bar -->
  <%= render 'layouts/navbar' %>

  <!-- Container to Display information -->
  <div class = "contenty">
    <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
  </div>

  <!-- Display Footer -->
  <%= render 'layouts/footer' %>
  
  <!-- JS for email, share and print buttons -->
  <script>
    var a2a_config = a2a_config || {};
    a2a_config.linkname = "Uni2choose - Check out my degree!";
    a2a_config.linkurl = window.location.href;
  </script>
  
  <!-- Share buttons end here -->
  <script async src="https://static.addtoany.com/menu/page.js"></script>
  
  <!-- JS for scotland regions popup -->
  <script type="text/javascript">
    Shadowbox.init();
  </script>
  
  <!-- Map pop up script ends here -->
  <%= javascript_include_tag 'banner.js'  %>
  <script type='text/javascript'>
		window.onload = function(){
		  generate();
		  };
	</script>

</body>

</html>